#!/usr/bin/env bash
# Id$ nonnax 2022-03-14 11:40:15 +0800
md_num="$1"
./scrape.rb "$md_num.md" |  kramdown - > "$md_num.html" 
cat head.html "$md_num.html" > tmp && cat tmp > "$md_num.html"
echo "$md_num.html" | pipefox
